const express = require('express');
const listingController = require('../controllers/listing.controller');
const router = express.Router();

/**
 * @swagger
 * components:
 *   schemas:
 *     Listing:
 *       type: object
 *       required:
 *         - id
 *         - listing_date
 *         - broker
 *         - revenue
 *       properties:
 *         id:
 *           type: integer
 *           description: The auto-generated id of the listing
 *         listing_date:
 *           type: string
 *           format: date
 *           description: The date the listing was created
 *         broker:
 *           type: string
 *           description: The broker handling the listing
 *         revenue:
 *           type: number
 *           description: The revenue generated by the listing
 *       example:
 *         id: 42
 *         listing_date: "2021-05-31"
 *         broker: "Brooker N"
 *         revenue: 1000001
 */

/**
 * @swagger
 * tags:
 *   name: Listings
 *   description: The listings managing API
 */

/**
 * @swagger
 * /listings:
 *   post:
 *     summary: Create a new listing
 *     tags: [Listings]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Listing'
 *     responses:
 *       201:
 *         description: The listing was successfully created
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Listing'
 *       500:
 *         description: Some server error
 */
router.post('/listings', listingController.addListing);

router.get('/listings-data', listingController.getListingsData);

module.exports = router;
